language: d
sudo: required
dist: xenial

os:
 - linux

d:
 - dmd-2.091.1,dub
 - dmd-2.090.1,dub
 - ldc-1.21.0,dub
 - ldc-1.20.0,dub
 - gdc

matrix:
  fast_finish: true
  allow_failures:
   - d: gdc
   
env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

before_script:
 - if [[ "$DC" == "gdc" ]]; then docker build -t debtesting -f Dockerfile .; fi

script:
 - if [[ "$DC" == "gdc" ]]; then
    docker run -t -e DC=$DC -v `pwd`:/build debtesting
    dub test -b unittest-cov; fi
 - if [[ "$DC" != "gdc" ]]; then
   dub test --arch=$ARCH --build=unittest-cov; fi

after_success:
 - bash <(curl -s https://codecov.io/bash)

