sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.079.1
 - dmd-2.078.3
 - ldc-1.8.0
 - ldc-1.7.0
 - gdc

matrix:
  fast_finish: true
  allow_failures:
   - d: gdc
   - d: dmd-2.079.1
     os: linux
     env: ARCH=x86
   - d: dmd-2.078.3
     os: linux
     env: ARCH=x86
   - d: ldc-1.8.0
     os: linux
     env: ARCH=x86
   - d: ldc-1.7.0
     os: linux
     env: ARCH=x86
   
env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH --build=unittest-cov

after_success:
 - bash <(curl -s https://codecov.io/bash)

