sudo: false

os:
 - linux

language: d

d:
 - dmd-2.081.0
 - dmd-2.080.1
 - ldc-1.10.0
 - ldc-1.9.0
 - gdc

matrix:
  fast_finish: true
  allow_failures:
   - d: gdc
   - d: dmd-2.081.0
     os: linux
     env: ARCH=x86
   - d: dmd-2.080.1
     os: linux
     env: ARCH=x86
   - d: ldc-1.10.0
     os: linux
     env: ARCH=x86
   - d: ldc-1.9.0
     os: linux
     env: ARCH=x86
   
env: 
  matrix:
    - ARCH=x86
    - ARCH=x86_64

addons:
  apt:
    packages:
     - gcc-multilib

script:
 - dub test --arch=$ARCH --build=unittest-cov

after_success:
 - bash <(curl -s https://codecov.io/bash)

